try

diff --git a/config/hooks/pre-push b/config/hooks/pre-push
--- a/config/hooks/pre-push
+++ b/config/hooks/pre-push
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # An example hook script to verify what is about to be pushed.  Called by "git
 # push" after it has checked the remote status, but before anything has been
@@ -19,37 +19,24 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
-remote="$1"
-url="$2"
+protected_branch='master'
 
-z40=0000000000000000000000000000000000000000
+while read local_ref local_sha remote_ref remote_sha; do
 
-while read local_ref local_sha remote_ref remote_sha
-do
-        echo $remote $url $local_ref $local_sha $remote_ref $remote_sha
-#        if [ "$local_sha" = $z40 ]
-#        then
-#                # Handle delete
-#                :
-#        else
-#                if [ "$remote_sha" = $z40 ]
-#                then
-#                        # New branch, examine all commits
-#                        range="$local_sha"
-#                else
-#                        # Update to existing branch, examine new commits
-#                        range="$remote_sha..$local_sha"
-#                fi
-#
-#                # Check for WIP commit
-#                commit=`git rev-list -n 1 --grep '^WIP' "$range"`
-#                if [ -n "$commit" ]
-#                then
-#                        echo >&2 "Found WIP commit in $local_ref, not pushing"
-#                        exit 1
-#                fi
-#        fi
+  if [[ "$remote_ref" == *"$protected_branch" ]]; then
+
+    REPO_ROOT_DIR=$(git rev-parse --show-toplevel)
+
+    "$REPO_ROOT_DIR/gradlew" check
+
+    # store the last exit code in a variable
+    RESULT=$?
+
+    # return the './gradlew test' exit code
+    exit $RESULT
+
+  fi
+
 done
 
 exit 0
-
